version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - fannheyward
- package-ecosystem: npm
  directory: "/template"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - fannheyward
  versioning-strategy: widen
